stages:
  - test

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - $HOME/.cache/pip

precommit:
  stage: test
  image: python:3
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  script:
    - pip3 install pre-commit
    - pre-commit run --all-files
  cache:
    paths:
      - ${PRE_COMMIT_HOME}

test:
  stage: test
  image: $IMAGE
  script:
    - pip install tox
    - tox --skip-missing-interpreters
  parallel:
    matrix:
      - IMAGE: python:3.8
      - IMAGE: python:3.9
      - IMAGE: python:3.10
